import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.css";
import Head from "next/head";
import { AnimatePresence } from "framer-motion";

import { store } from "../store";
import { Provider } from "react-redux";

function MyApp({ Component, pageProps }) {
  return (
    <AnimatePresence>
      <Provider store={store}>
        <Head>
          <title>NextJS Todo App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="container">
          <Component {...pageProps} />
        </div>
      </Provider>
    </AnimatePresence>
  );
}

export default MyApp;
