import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/todo");
  const data = await res.json();
  return {
    props: {
      // todos: JSON.parse(JSON.stringify(data)),
      todos: data,
    },
  };
}

export default function Home({ todos }) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");

  useEffect(() => {
    console.log(todos);
  }, []);

  const formSubmitHandler = async (e) => {
    e.preventDefault();
    await fetch("/api/todo", {
      method: "POST",
      body: JSON.stringify({ title, description }),
      headers: {
        "Content-Type": "application/json",
      },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={formSubmitHandler}>
          <label htmlFor="title">Title</label>
          <input
            type="text"
            name="title"
            id="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <label htmlFor="description">Description</label>
          <input
            type="text"
            name="description"
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
          <button>Submit</button>
        </form>
        {todos?.length === 0 ? (
          <p>Loading...</p>
        ) : (
          todos.data.map((todo) => (
            <div key={todo._id}>
              {todo.title} - {todo.description}
            </div>
          ))
        )}
      </main>
    </div>
  );
}
